import { ICar } from "../models";

export const CARS: ICar[] = [
  {
    id: 1,
    name: "BMW",
    model: "X5",
    price: 10000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 2,
    name: "Mercedes",
    model: "S500",
    price: 12000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 3,
    name: "Audi",
    model: "A6",
    price: 8000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 4,
    name: "Lada",
    model: "Kalina",
    price: 3000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 5,
    name: "Nissan",
    model: "Almera",
    price: 4000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 1,
    name: "BMW",
    model: "X5",
    price: 10000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 2,
    name: "Mercedes",
    model: "S500",
    price: 12000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 3,
    name: "Audi",
    model: "A6",
    price: 8000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 4,
    name: "Lada",
    model: "Kalina",
    price: 3000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 5,
    name: "Nissan",
    model: "Almera",
    price: 4000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 1,
    name: "BMW",
    model: "X5",
    price: 10000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 2,
    name: "Mercedes",
    model: "S500",
    price: 12000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 3,
    name: "Audi",
    model: "A6",
    price: 8000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 4,
    name: "Lada",
    model: "Kalina",
    price: 3000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 5,
    name: "Nissan",
    model: "Almera",
    price: 4000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 1,
    name: "BMW",
    model: "X5",
    price: 10000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 2,
    name: "Mercedes",
    model: "S500",
    price: 12000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 3,
    name: "Audi",
    model: "A6",
    price: 8000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 4,
    name: "Lada",
    model: "Kalina",
    price: 3000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 5,
    name: "Nissan",
    model: "Almera",
    price: 4000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 6,
    name: "Toyota",
    model: "Corolla",
    price: 5000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 7,
    name: "Volkswagen",
    model: "Polo",
    price: 6000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 8,
    name: "Renault",
    model: "Logan",
    price: 7000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 9,
    name: "Ford",
    model: "Focus",
    price: 9000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 10,
    name: "Mazda",
    model: "6",
    price: 10000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 11,
    name: "Kia",
    model: "Rio",
    price: 11000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
  {
    id: 12,
    name: "Hyundai",
    model: "Accent",
    price: 12000,
    mileage: 1000,
    colors: [
      "red",
      "blue",
      "green",
      "black",
      "white",
      "yellow",
      "silver",
      "gold",
    ],
    acceleration: 3.2,
    braking: 2.5,
    damage: 0,
    maxSpeed: 250,
  },
];

export const PARAMETERS_CARS = [
  { id: 1, name: "Mileage" },
  { id: 2, name: "Max Speed" },
  { id: 3, name: "Capacity" },
  { id: 4, name: "Permadamage" },
  { id: 5, name: "Acceleration" },
  { id: 6, name: "Braking" },
];
